name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install tidy
      - if: matrix.os == 'windows-latest'
        run: |
          choco install html-tidy
      - name: Configure git
        run: |
          git config --global user.email "ki@example.com"
          git config --global user.name "Ki GithubActions"
      - name: Install dependencies
        run: |
          pip install pytest wheel
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: Install ki
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pytest -vv --timeout=120 tests/test_integration.py
